# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import time
import numpy as np
sys.path.append('../imgProcessing')
sys.path.append('../support_class')

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
from PyQt5.QtCore import QTimer
# import OpenCVforRaspberry
from BackgroundWorker import *
from ImgProClass import *

class Ui_overView(object):
    def __init__(self):
        self.background_worker = None
        self.imgProc = ImgProcessing()

    def setupUi(self, overView):
        overView.setObjectName("overView")
        overView.resize(800, 500)
        overView.setGeometry(QtCore.QRect(100, 80, 800, 500))
        overView.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        overView.setAcceptDrops(False)
        overView.setToolTipDuration(1)
        overView.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        overView.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(overView)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 250, 500))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: white;")
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(3)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.logo = QtWidgets.QLabel(self.frame)
        self.logo.setGeometry(QtCore.QRect(85, 120, 80, 120))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("/home/pi/Desktop/TheLastProjectAtUnivesity/Python/img/UniversityLogo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.Information = QtWidgets.QTextBrowser(self.frame)
        self.Information.setGeometry(QtCore.QRect(3, 10, 244, 110))
        self.Information.setStyleSheet("font: 8pt \"Ubuntu\";")
        self.Information.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Information.setLineWidth(0)
        self.Information.setObjectName("Information")
        self.projectName = QtWidgets.QTextBrowser(self.frame)
        self.projectName.setGeometry(QtCore.QRect(3, 270, 244, 50))
        font = QtGui.QFont()
        font.setKerning(True)
        self.projectName.setFont(font)
        self.projectName.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.projectName.setLineWidth(0)
        self.projectName.setObjectName("projectName")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser.setGeometry(QtCore.QRect(3, 330, 70, 70))
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser_2.setGeometry(QtCore.QRect(54, 330, 190, 192))
        self.textBrowser_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser_3.setGeometry(QtCore.QRect(3, 240, 244, 30))
        self.textBrowser_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.workPlace = QtWidgets.QFrame(self.centralwidget)
        self.workPlace.setGeometry(QtCore.QRect(250, 0, 550, 600))
        self.workPlace.setStyleSheet("background-color:rgb(56, 48, 58);")
        self.workPlace.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.workPlace.setFrameShadow(QtWidgets.QFrame.Raised)
        self.workPlace.setObjectName("workPlace")
        self.stackedWidget = QtWidgets.QStackedWidget(self.workPlace)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 550, 600))
        self.stackedWidget.setStyleSheet("background-color: rgb(34, 29, 29);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_start = QtWidgets.QWidget()
        self.page_start.setObjectName("page_start")
        self.start_buttom = QtWidgets.QPushButton(self.page_start)
        self.start_buttom.setGeometry(QtCore.QRect(130, 180, 301, 130))
        self.start_buttom.setStyleSheet("\n"
"background-color: rgb(78, 154, 6);\n"
"color: rgb(255, 255, 255);\n"
"font: 30pt \"Waree\";\n"
"border-radius: 50px;")
        self.start_buttom.setObjectName("start_buttom")
        self.name_speed = QtWidgets.QLabel(self.page_start)
        self.name_speed.setGeometry(QtCore.QRect(10, 10, 261, 60))
        self.name_speed.setStyleSheet("color: white;\n"
"font: 25pt \"Umpush\";")
        self.name_speed.setObjectName("name_speed")
        self.comboBox = QtWidgets.QComboBox(self.page_start)
        self.comboBox.setGeometry(QtCore.QRect(270, 20, 101, 41))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 15pt \"Ubuntu\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.stackedWidget.addWidget(self.page_start)
        self.page_loading = QtWidgets.QWidget()
        self.page_loading.setObjectName("page_loading")
        self.loading_bar = QtWidgets.QProgressBar(self.page_loading)
        self.loading_bar.setGeometry(QtCore.QRect(75, 300, 400, 23))
        self.loading_bar.setStyleSheet("QProgressBar{    \n"
"    color: red;\n"
"    background-color: white;\n"
"    border-style:none;\n"
"    border-radius:10px;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius:10px;\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.0199005, y1:0.534091, x2:0.965, y2:0.545455, stop:0 rgba(190, 57, 57, 255), stop:1 rgba(204, 0, 0, 255));\n"
"}")
        self.loading_bar.setProperty("value", 35)
        self.loading_bar.setObjectName("loading_bar")
        self.loadin_word = QtWidgets.QLabel(self.page_loading)
        self.loadin_word.setGeometry(QtCore.QRect(0, 250, 550, 40))
        self.loadin_word.setStyleSheet("font: 17pt \"C059\";")
        self.loadin_word.setObjectName("loadin_word")
        self.stackedWidget.addWidget(self.page_loading)
        self.page_stop = QtWidgets.QWidget()
        self.page_stop.setObjectName("page_stop")
        self.stop_buttom = QtWidgets.QPushButton(self.page_stop)
        self.stop_buttom.setGeometry(QtCore.QRect(20, 20, 161, 81))
        self.stop_buttom.setStyleSheet("color: rgb(238, 238, 236);\n"
"font: 25pt \"Umpush\";\n"
"background-color: rgb(164, 0, 0);\n"
"border-radius: 20px")
        self.stop_buttom.setObjectName("stop_buttom")
        self.label = QtWidgets.QLabel(self.page_stop)
        self.label.setGeometry(QtCore.QRect(50, 130, 100, 100))
        self.label.setStyleSheet("QFrame{border: 3px solid white; border-radius:50px}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.performance = QtWidgets.QLabel(self.page_stop)
        self.performance.setGeometry(QtCore.QRect(70, 160, 70, 35))
        self.performance.setStyleSheet("font: 25pt \"Ubuntu\";\n"
"color: white;")
        self.performance.setObjectName("performance")
        self.label_3 = QtWidgets.QLabel(self.page_stop)
        self.label_3.setGeometry(QtCore.QRect(260, 10, 150, 50))
        self.label_3.setStyleSheet("color: white;\n"
"font: 22pt \"Umpush\";")
        self.label_3.setObjectName("label_3")
        self.num_detected = QtWidgets.QLabel(self.page_stop)
        self.num_detected.setGeometry(QtCore.QRect(410, 14, 80, 50))
        self.num_detected.setStyleSheet("font: 22pt \"Umpush\";\n"
"color: white;")
        self.num_detected.setObjectName("num_detected")
        self.label_5 = QtWidgets.QLabel(self.page_stop)
        self.label_5.setGeometry(QtCore.QRect(260, 60, 160, 50))
        self.label_5.setStyleSheet("color: white;\n"
"font: 22pt \"Umpush\";")
        self.label_5.setObjectName("label_5")
        self.num_done = QtWidgets.QLabel(self.page_stop)
        self.num_done.setGeometry(QtCore.QRect(380, 64, 67, 50))
        self.num_done.setStyleSheet("color: white;\n"
"font: 22pt \"Umpush\";")
        self.num_done.setObjectName("num_done")
        self.image_detect = QtWidgets.QLabel(self.page_stop)
        self.image_detect.setGeometry(QtCore.QRect(70, 250, 410, 240))
        self.image_detect.setText("")
        self.image_detect.setPixmap(QtGui.QPixmap("../Documents/Study/python-test/a.jpg"))
        self.image_detect.setScaledContents(True)
        self.image_detect.setObjectName("image_detect")
        self.stackedWidget.addWidget(self.page_stop)
        overView.setCentralWidget(self.centralwidget)

        self.retranslateUi(overView)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(overView)

    def retranslateUi(self, overView):
        _translate = QtCore.QCoreApplication.translate
        overView.setWindowTitle(_translate("overView", "Cải tiến hệ thống điều khiển Robot BK-Delta"))
        self.Information.setHtml(_translate("overView", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:11px; margin-bottom:11px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Đại học Bách khoa Hà Nội</span></p>\n"
"<p align=\"center\" style=\" margin-top:11px; margin-bottom:11px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Viện Cơ khí</span></p>\n"
"<p align=\"center\" style=\" margin-top:11px; margin-bottom:11px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Bộ môn Công nghệ Chế tạo máy</span></p></body></html>"))
        self.projectName.setHtml(_translate("overView", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Cải tiến hệ thống điều khiển Robot BK-Delta</p></body></html>"))
        self.textBrowser.setHtml(_translate("overView", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">GVHD:</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">SVTH:</p></body></html>"))
        self.textBrowser_2.setHtml(_translate("overView", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TS. Nguyễn Văn Tình</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Nguyễn Văn Phi ---20163129---</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Lê Quang Thành ---20163702---</p></body></html>"))
        self.textBrowser_3.setHtml(_translate("overView", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" text-decoration: underline;\">Đề tài:</span></p></body></html>"))
        self.start_buttom.setText(_translate("overView", "START"))
        self.name_speed.setText(_translate("overView", "<html><head/><body><p align=\"center\">Chọn tốc độ:</p></body></html>"))
        self.comboBox.setItemText(0, _translate("overView", "1"))
        self.comboBox.setItemText(1, _translate("overView", "2"))
        self.comboBox.setItemText(2, _translate("overView", "3"))
        self.loadin_word.setText(_translate("overView", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#cc0000;\">loading...</span></p></body></html>"))
        self.stop_buttom.setText(_translate("overView", "STOP"))
        self.performance.setText(_translate("overView", "<html><head/><body><p align=\"center\">0%</p></body></html>"))
        self.label_3.setText(_translate("overView", "<html><head/><body><p>Phát hiện:</p></body></html>"))
        self.num_detected.setText(_translate("overView", "3"))
        self.label_5.setText(_translate("overView", "<html><head/><body><p>Đã diệt:</p></body></html>"))
        self.num_done.setText(_translate("overView", "0"))

        self.start_buttom.clicked.connect(self.btn_start)
        self.stop_buttom.clicked.connect(self.reset)

    def btn_start(self):
        self.stackedWidget.setCurrentIndex(1)
        image, confidence, class_ids, boxes, indices, num_x = self.imgProc.detect_img()
        height, width, channel = image.shape
        bytesPerLine = 3 * width
        qImg = QImage(image.data, width, height, bytesPerLine, QImage.Format_RGB888).rgbSwapped()
        #self.num_detected.setText(str(np.array(indices).shape[0]))
        self.num_detected.setText(str(num_x))
        self.image_detect.setPixmap(QtGui.QPixmap(qImg))
        self.background_worker = worker(indices, boxes, class_ids, self)
        QTimer.singleShot(10, self.work)

    def work(self):
        print('11')
        self.stackedWidget.setCurrentIndex(2)
        listS=[500,400,300]
        speed = listS[int(self.comboBox.currentText()) - 1]
        self.background_worker.start()

    def update_num_done(num):
        self.num_done.setText(str(num))

    def reset(self):
        self.stackedWidget.setCurrentIndex(0)

    def release_resource(self):
        self.background_worker.kill()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    overView = QtWidgets.QMainWindow()
    ui = Ui_overView()
    ui.setupUi(overView)
    overView.show()
    sys.exit(app.exec_())
